### ISSUE TITLE
The script after some time stops.

### ISSUE THREAD

**Issue by kozyty** [rubenmak/PokemonGo-SlackBot#12]
I run it for some days now, and I face an issue. The script after some time stops searching or at least stops providing feed to slack channel. 

https://www.themarketingtechnologist.co/pokemon-go-slack-notifications/#comment-2803817460

me too.

**Comment by RPGReki** [comment]
Duplicate of issue #2.

**Comment by rubenmak** [comment]
I merged a fix that needs to be tested to the develop branch, see: https://github.com/rubenmak/PokemonGo-SlackBot/issues/2

Feel free to test it and share your findings if you like!

**Comment by kozyty** [comment]
thanks! merged to #2 , this issue will closed.
