### ISSUE TITLE
Crash when location is point of interest

### ISSUE THREAD

**Issue by Hirza-Tango** [rubenmak/PokemonGo-SlackBot#13]
The program crashes, even though python is updated, it is run as su and all dependencies are met.

Attached is the backtrace.

The command exectuted was ./pokeslack.py -a google -u foo@bar.com -p foobar -r 250 -st 2 -l "Valid location" -sw "/services/foo/bar/foobar"
[backtrace.txt](https://github.com/rubenmak/PokemonGo-SlackBot/files/387130/backtrace.txt)

**Comment by rubenmak** [comment]
Can you find the results of these prints in your console?

print '[!] Your given location: {}'.format(loc.address.encode('utf-8'))
print('[!] lat/long/alt: {} {} {}'.format(local_lat, local_lng, alt))

**Comment by Hirza-Tango** [comment]
No. The full output looks like this:

[-] register_background_thread called
[-] register_background_thread: not running inside Flask so not starting thread
- Restarting with stat
  [-] register_background_thread called
  [-] register_background_thread: initial registration
- Debugger is active!
- Debugger pin code: 903-942-853
  [+] Locale is en
  [+] Getting initial location
- Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
  Exception in thread search_thread:
  Traceback (most recent call last):

**Comment by Hirza-Tango** [comment]
I've manage to get it working when the location is a city or address, but not when it's a point of interest, as it originally was.

**Comment by rubenmak** [comment]
Ok, well I'm not sure what we can do about it since it's just using the Google Maps API to do so. So if it was working before, it should be because of a change in that API. Hope it also works for you like this!
