### ISSUE TITLE
Can't login with non-alphanumeric password

### ISSUE THREAD

**Issue by VincentGarreau** [rubenmak/PokemonGo-SlackBot#17]
## Command

`python pokeslack.py -u email@gmail.com -p -password.Example;? [...]`
## Results

`pokeslack.py: error: argument -p/--password: expected one argument`
`-bash: ?: command not found`

**Comment by rubenmak** [comment]
-password.Example why the - here? that makes it a new argument. You can try putting your password in quotes:

python pokeslack.py -u email@gmail.com -p 'password' -a google [...]

don't forget -a google is you use a google account

**Comment by VincentGarreau** [comment]
Thanks! I tried to wrap the password with simple / double quotes but i had this error:
`pokeslack.py: error: argument -p/--password: expected one argument`

**Comment by rubenmak** [comment]
uhm the problem is that I can't see what your password is. Could be that you for example need to escape characters (using )?

Or couldn't you change your password? Might be the most easy thing to do!

**Comment by VincentGarreau** [comment]
Ok no problem, i'll try to espace characters. Thank you for your help!
