### ISSUE TITLE
wrong username/password

### ISSUE THREAD

**Issue by RoySadaka** [rubenmak/PokemonGo-SlackBot#20]
it says Wrong username/password when i run it.. say my email in slack when i registered was: myEmail@gmail.com 
and password is:
MyPassword32
so i ran the command like this:
python pokeslack.py -u myEmail -p MyPassword32 -l “some place on google maps” -st 1 -r 10 -sw “my url from web hook slack”
Is this the right way? cause it throw an exception of Wrong username/password

**Comment by rubenmak** [comment]
Use your full email address and add -a google for google authentication.

**Comment by RoySadaka** [comment]
trying:
python pokeslack.py -u myEmail@gmail.com -p MyPassword32 -a google -l “some place on google maps” -st 1 -r 10 -sw “my url from webhook slack”
is resulting the same error (replaced private data with ######), and i can login to slack with that email and password:
[-] register_background_thread called
[-] register_background_thread: not running inside Flask so not starting thread
- Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
- Restarting with stat
  [-] register_background_thread called
  [-] register_background_thread: initial registration
  [+] Locale is en
- Debugger is active!
  [+] Getting initial location
- Debugger pin code: 247-384-902
  [!] Your given location: ######
  [!] lat/long/alt: ###### ###### ######
  [!] Google login for: ######@gmail.com
  Exception in thread search_thread:
  Traceback (most recent call last):
  File "/Users/######/anaconda/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/Users/######/anaconda/lib/python2.7/threading.py", line 754, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "pokeslack.py", line 679, in main
    api_endpoint, access_token, profile_response = login(args)
  File "pokeslack.py", line 99, in memoizer
    cache[key] = obj(_args, *_kwargs)
  File "pokeslack.py", line 614, in login
    raise Exception('[-] Wrong username/password')
  Exception: [-] Wrong username/password

Appreciate your help!

**Comment by rubenmak** [comment]
Are you inputting your slack credentials at -u and -p ? It should be the credentials of the new Pokemon player (either PTC or Google credentials) you made (I suggest not using your private credentials...) for running the applications.
