### ISSUE TITLE
Missing package numpy after latest pull

### ISSUE THREAD

**Issue by tinifni** [rubenmak/PokemonGo-SlackBot#21]
After the latest pull, I received the following error.

``` sh
Traceback (most recent call last):
  File "pokeslack.py", line 25, in <module>
    import numpy as np
ImportError: No module named numpy
```

Installing the missing package fixed my issue.

``` sh
pip install numpy
```

Maybe it needs to be added to the `requirements.txt`?

**Comment by rubenmak** [comment]
Thanks! As a data scientist I'm so used to using numpy that I forgot to add it ;)

**Comment by Hirza-Tango** [comment]
Shouldn't the requirements.txt be in Easy Setup?
