### ISSUE TITLE
Minor: How to get Pokemon's name as a variable in language files?

### ISSUE THREAD

**Issue by tkreindler** [rubenmak/PokemonGo-SlackBot#25]
Slack's notifications don't include the pokemon's name, so my solution would be to put something along the lines of #{latitude} but for pokemon name, however I can't figure out how to do this.

**Comment by rubenmak** [comment]
Why would you want the Pokemon's name in the messages if it's already the
username that sends you the message?

**Comment by tkreindler** [comment]
Because when you get a notification on the iOS lock screen, it doesn't show the username of who sent it.

**Comment by rubenmak** [comment]
Check, a colleague just happened to ask me for the same thing today! I fixed it, hope it works for you now :)
