### ISSUE TITLE
Connected with MFA enabled Google Account

### ISSUE THREAD

**Issue by plastikdreams** [rubenmak/PokemonGo-SlackBot#6]
Hi, it's great your slackbot!

I had tried to use script with my PokemonGO account connected with my MFA enabled Google account (not Pokémon Trainer Club account), but I could not login with this script.
It returned following error.

```
[!] Google login for: CONNECTED-MY-ACCOUNT@gmail.com
Exception in thread search_thread:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 813, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 766, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./pokeslack.py", line 674, in main
    api_endpoint, access_token, profile_response = login(args)
  File "./pokeslack.py", line 98, in memoizer
    cache[key] = obj(*args, **kwargs)
  File "./pokeslack.py", line 609, in login
    raise Exception('[-] Wrong username/password')
Exception: [-] Wrong username/password
```

Do you have any plans to enable login with PokemonGO account connected with my MFA enabled Google account?

Thank you in advance.

**Comment by rubenmak** [comment]
add -a google to your command! It was also mentioned in the comments below the article, so I update the post to explain it!

Hope it works for you now!
